---
- hosts:        all
  gather_facts: true
  remote_user:  root

  pre_tasks:
  - name: Update apt cache
    apt: update_cache=yes

  - name: Upgrade packages
    apt: upgrade=yes

  - name: Install software-properties-common
    apt:
      name: software-properties-common
      state: latest


  roles:
    - role: jhuesser.baseserver

  post_tasks:
  - name: restart machine
    become: yes
    shell: sleep 2 && shutdown -r now "Ansible triggered after deployment reboot"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Waiting for server to come back
    become: no
    local_action: wait_for
      port=22
      host={{ inventory_hostname }}
      search_regex=OpenSSH
      delay=10

  - name: Remove existing docker packages
    apt:
      name:
        - docker
        - docker-engine 
        - docker.io 
        - containerd 
        - runc
      state: absent

  - name: Install pre reqs
    apt:
      name:
       - ca-certificates
       - curl
       - gnupg
       - lsb-release
    state: latest

  - name: Get GPG keys
    command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: add repo to sources.list
    command: echo  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Install packages
    apt:
      update_cache: yes
      name:
        - docker-ce
        - docker-ce-cli 
        - containerd.io

  - name: Get docker-compose
    command: curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: Change permissions
    file:
      path: /usr/local/bin/docker-compose
      mode: a+x