---
- hosts:        all
  gather_facts: true
  remote_user:  root

  pre_tasks:
  - name: Update apt cache
    apt: update_cache=yes

  - name: Upgrade packages
    apt: upgrade=yes

  - name: Install software-properties-common
    apt:
      name: software-properties-common
      state: latest


  roles:
    - role: jhuesser.baseserver

  post_tasks:
  - name: restart machine
    become: yes
    shell: sleep 2 && shutdown -r now "Ansible triggered after deployment reboot"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Waiting for server to come back
    become: no
    local_action: wait_for
      port=22
      host={{ inventory_hostname }}
      search_regex=OpenSSH
      delay=10
